package util;

public class Path {
    public static final String incomeBtnId = "income_button";
    public static final String expenseBtnId = "expense_button";
    public static final String balanceBtnId = "balance_amount";
    public static final String amountField = "amount_text";
    public static final String noteFieldId = "textViewNote";
    public static final String chooseCategoryId = "keyboard_action_button";
    public static final String btnId0 = "buttonKeyboard0";
    public static final String btnId1 = "buttonKeyboard1";
    public static final String btnId2 = "buttonKeyboard2";
    public static final String btnId3 = "buttonKeyboard3";
    public static final String btnId4 = "buttonKeyboard4";
    public static final String btnId5 = "buttonKeyboard5";
    public static final String btnId6 = "buttonKeyboard6";
    public static final String btnId7 = "buttonKeyboard7";
    public static final String btnId8 = "buttonKeyboard8";
    public static final String btnId9 = "buttonKeyboard9";
    public static final String listSortBtnId = "buttonChooseListSortingMode";
    public static final String moreOptionBtn = "overflow";
    public static final String settingsBtnId = "settings_button";
    public static final String dataBackUpBtnId = "backup_database_button";
    public static final String dataRestoreBtnId = "restore_database_button";
    public static final String dataClearBtnId = "clear_database_button";
    public static final String dataConfirmBtnId = "button1";
    public static final String depositBtnXpath = "//*[@text='Deposits']";
    public static final String salaryBtnXpath = "//*[@text='Salary']";
    public static final String savingBtnXpath = "//*[@text='Savings']";
    public static final String billsBtnXpath = "//*[@text='Bills']";
    public static final String carBtnXpath = "//*[@text='Car']";
    public static final String clotheBtnXpath = "//*[@text='Clothes']";
    public static final String communicationBtnXpath = "//*[@text='Communications']";
    public static final String eatingOutBtnXpath = "//*[@text='Eating out']";
    public static final String entertainmentBtnXpath = "//*[@text='Entertainment']";
    public static final String foodBtnXpath = "//*[@text='Food']";
    public static final String giftsBtnXpath = "//*[@text='Gifts']";
    public static final String healthBtnXpath = "//*[@text='Health']";
    public static final String houseBtnXpath = "//*[@text='House']";
    public static final String petsBtnXpath = "//*[@text='Pets']";
    public static final String sportsBtnXpath = "//*[@text='Sports']";
    public static final String taxiBtnXpath = "//*[@text='Taxi']";
    public static final String toileteryBtnXpath = "//*[@text='Toiletry']";
    public static final String transportBtnXpath = "//*[@text='Transport']";
    public static final String accountDropDownXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.LinearLayout/android.widget.FrameLayout/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout[2]/android.widget.ScrollView/android.widget.LinearLayout/android.widget.RadioGroup/android.widget.Spinner/android.widget.LinearLayout/android.widget.LinearLayout";
    public static final String allAccBtnXpath = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[1]/android.widget.LinearLayout";
    public static final String cashBtnXpath = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[2]/android.widget.LinearLayout";
    public static final String cardBtnXpath = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[3]/android.widget.LinearLayout/android.widget.TextView";
    public static final String menuBtnXpath = "//android.widget.ImageButton[@content-desc=\"Open navigation\"]";
    public static final String menuBackBtnXpath = "//android.widget.ImageButton[@content-desc=\"Close navigation\"]";
    public static final String transferBtnId = "transfer_menu_item";
    public static final String transferPageAmountBtnId = "amount_text";
    public static final String transferPageNoteFieldId = "textViewNote";
    public static final String transferPageFirstDropDownXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.Spinner[1]/android.widget.LinearLayout/android.widget.LinearLayout";
    public static final String transferPageSecondDropDownXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.RelativeLayout/android.widget.Spinner[2]";
    public static final String transferPageFirstDropDownCashXpath = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[1]/android.widget.LinearLayout";
    public static final String transferPageFirstDropDownCardXpath = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[2]/android.widget.LinearLayout";
    public static final String transferPageSecondtDropDownCashXpath = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[1]/android.widget.LinearLayout";
    public static final String transferPageSecondDropDownCardXpath = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.TextView";
    public static final String addTransferButtonXpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.Button";
    public static final String accountSpinnerId = "account_spinner";
    public static final String accountSpinnerCashXpath = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[1]";
    public static final String accountSpinnerCardXpath = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[2]";
    public static final String leftMenuId = "eftLinesImageView";
}
